languages:
    Ruby: false
    JavaScript: true
    PHP: true
    Python: false
exclude_paths:
    - "vendor/*"
    - "config/*"
    - "bootstrap/*"
    - "database/*"
    - "storage/*"
    - "resources/assets/css/skin-*.css"
    - "resources/assets/js/AdminLTE.js"
    - "resources/assets/css/AdminLTE.css"
    - "resources/lang/en/*.php"
    - "*.blade.php"
    - "*.js"
