#!/usr/bin/env bash

# Check that a github token exists in CHANGELOG_GITHUB_TOKEN
while [[ "$CHANGELOG_GITHUB_TOKEN" =~ ^$  ]]
do
    read -p 'Github token not set: ' GITHUB_TOKEN
    export CHANGELOG_GITHUB_TOKEN=$GITHUB_TOKEN
done

# TODO: Stash changes here

git checkout master

git pull

# Get the current latest release tag from github - FIXME: Actually test this returns a valid response otherwise exit
CURRENT_VERSION=`curl --silent https://api.github.com/repos/REBELinBLUE/deployer/releases/latest | php -r 'echo json_decode(file_get_contents("php://stdin"))->tag_name;'`

# Remove -dev from the version in the VERSION file
NEW_VERSION=`sed 's/-dev//' VERSION`

# Generate change log
github_changelog_generator --future-release $NEW_VERSION

# Ask for the name of the next version
while [[ "$NEXT_VERSION" =~ ^$  ]]
do
    read -p 'Enter the next version: ' NEXT_VERSION
done

# Append -dev and update the VERSION file
echo -n $NEXT_VERSION > VERSION
echo '-dev' >> VERSION

# FIXME: Ask for confirmation on wheather to do this
# Replace the current version with the new version in the README
# sed -i "s/checkout $CURRENT_VERSION/checkout $NEW_VERSION/g" README.md

# Commit the updated files
git add CHANGELOG.md VERSION README.md
git commit -m 'Updated CHANGELOG'
git push

# Switch to the release branch and merge master into it, overwriting any conflicts with the version in mast
git checkout release
git merge --no-edit -q -X theirs master

# Set the new version
echo $NEW_VERSION > VERSION

git add VERSION

# Remove the compiled assets
git rm -rf public/build/*
rm -rf public/build/

# Ensure all dependencies are installed
npm install
composer install

# Build the CSS/JS
gulp --production

git add -f public/build/rev-manifest.json
git add -f public/build/css/*.css
git add -f public/build/js/*.js
git add -f public/build/fonts/*

# TODO: Should we maybe remove things we don't need in a release like the raw CSS/JS from resources and the various files from .gitattributes?

# Commit the build and switch back to master
git commit -am 'Building new release'
git push

# TODO: Maybe use https://github.com/aktau/github-release to actually create a release?

git checkout master
git branch -D release

# Build the assets as switching back would have removed them
gulp

# TODO: Only pop if we made a new stash
#git stash pop
