<?php

return [

    'name'              => 'Name',
    'email'             => 'Email',
    'password'          => 'Password',
    'password_confirm'  => 'Password Confirmation',
    'password_existing' => 'Password (leave blank to leave unchanged)',
    'create'            => 'Add a new user',
    'edit'              => 'Edit a user',
    'warning'           => 'The user could not be saved, please check the form below.',
    'manage'            => 'Manage users',
    'profile'           => 'Profile',
    'update_profile'    => 'Update Profile',
    'basic'             => 'Basic',
    'change_password'   => 'Change Password',
    'settings'          => 'Settings',
    '2fa'               => 'Security',
    'enable_2fa'        => 'Enable two factor authentication',
    '2fa_help'          =>  'Enabling two factor authentication increases security of your account. You need to ' .
                            'download <a href="https://support.google.com/accounts/answer/1066447?hl=en" target="_blank">' .
                            'Google Authenticator</a> or a similar app. When you login you will be asked to provide a security ' .
                            'token generated by the app.',
    'theme'             => 'Theme',
    'change_email'      => 'Email Address',
    'save'              => 'Save',
    'current_name'      => 'Current Name',
    'request_confirm'   => 'Request Change',
    'avatar'            => 'Avatar',
    'enter_email'       => 'Enter your new email',
    'upload'            => 'Upload new image',
    'reset_gravatar'    => 'Use Gravatar',
    'email_sent'        => 'Please check your email, you have been sent a link to change your email address',
    'avatar_success'    => 'Your avatar has been saved successfully!',
    'avatar_failed'     => 'Your avatar could not be saved',
    'yellow'            => 'Yellow',
    'red'               => 'Red',
    'green'             => 'Green',
    'purple'            => 'Purple',
    'blue'              => 'Blue',
    'with_sidebar'      => ':colour with light sidebar',

];
