---
- name: Get deployer from repository
  git: repo="https://github.com/REBELinBLUE/deployer.git" dest={{deployer_directory}} version={{deployer_version}} force=yes update=yes
  register: version_modified

- name: Install deployer dependencies (Composer)
  composer: command="install" no_dev=yes optimize_autoloader=yes working_dir={{deployer_directory}}
  when: version_modified.changed

- name: Install deployer dependencies (NPM)
  npm: path={{deployer_directory}} production=yes
  when: version_modified.changed

- name: Set writable permissions for public directories
  file: path={{item}} mode=0777 recurse=yes state=directory
  with_items:
  - "{{deployer_directory}}/storage"
  - "{{deployer_directory}}/public/upload"

- name: Check if deployer configuration file exists
  stat: path={{deployer_directory}}/.env
  register: configuration_exists

- name: Install deployer configuration file
  template: src=env.deployer.j2 dest={{deployer_directory}}/.env

- name: Run scripts to complete deployer installation
  shell: "{{item}}"
  args:
    chdir: "{{deployer_directory}}"
  with_items:
  - "php artisan clear-compiled"
  - "php artisan cache:clear"
  - "php artisan route:clear"
  - "php artisan config:clear"
  - "php artisan view:clear"
  - "php artisan optimize --force"
  - "php artisan key:generate"
  - "php artisan jwt:generate"
  - "php artisan config:cache"
  - "php artisan route:cache"
  - "php artisan migrate --force"
  - "npm install --production"

- name: Update deployer
  shell: 'printf \"\yes\" | php artisan app:update'
  args:
    chdir: "{{deployer_directory}}"
  when: (configuration_exists.stat.exists == True and version_modified.changed == True)

- name: Create Deployer cron job
  cron: name="Deployer schedule" job="sudo php {{deployer_directory}}/artisan schedule:run 1>> /dev/null 2>&1"

- name: Create supervisor configuration file
  template: src=deployer.conf.j2 dest=/etc/supervisor/conf.d/deployer.conf
  notify: start supervisor
