---
- name: Activate repositories
  apt_repository: repo="{{item}}"
  with_items:
  - "deb http://archive.ubuntu.com/ubuntu trusty main"
  - "deb-src http://archive.ubuntu.com/ubuntu trusty main"
  - "deb http://archive.ubuntu.com/ubuntu trusty-updates main"
  - "deb-src http://archive.ubuntu.com/ubuntu trusty-updates main"
  - "deb http://archive.ubuntu.com/ubuntu trusty universe"
  - "deb-src http://archive.ubuntu.com/ubuntu trusty universe"
  - "deb http://archive.ubuntu.com/ubuntu trusty-updates universe"
  - "deb-src http://archive.ubuntu.com/ubuntu trusty-updates universe"
  - "deb http://archive.ubuntu.com/ubuntu trusty multiverse"
  - "deb-src http://archive.ubuntu.com/ubuntu trusty multiverse"
  - "deb http://archive.ubuntu.com/ubuntu trusty-updates multiverse"
  - "deb-src http://archive.ubuntu.com/ubuntu trusty-updates multiverse"
  - "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
  - "deb-src http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
  - "deb http://security.ubuntu.com/ubuntu trusty-security main"
  - "deb-src http://security.ubuntu.com/ubuntu trusty-security main"
  - "deb http://security.ubuntu.com/ubuntu trusty-security universe"
  - "deb-src http://security.ubuntu.com/ubuntu trusty-security universe"
  - "deb http://security.ubuntu.com/ubuntu trusty-security multiverse"
  - "deb-src http://security.ubuntu.com/ubuntu trusty-security multiverse"

- name: Update repository cache
  apt: update_cache=yes

- name: Install basic packages
  apt: name={{item}} state=latest
  with_items: basic_packages

- name: Install supervisor
  command: easy_install supervisor

- name: Configure supervisor
  command: mkdir -p /etc/supervisor/conf.d

- name: Configure supervisor
  command: echo_supervisord_conf > /etc/supervisord.conf

- name: Create www-data group
  group: name=www-data

- name: Create www-data user
  user: name=www-data group=www-data createhome=no
