---
- name: Install MySQL Server
  apt: name=mysql-server={{mysql_version}}

- name: Create database
  mysql_db: name={{database_deployer_name}}

- name: Add MySQL user
  mysql_user: name={{database_deployer_user}} password={{database_deployer_pwd}} priv={{database_deployer_name}}.*:ALL,GRANT
