# Customize the domain for your application. Remember that you will need to either create a dns record or modify your hosts file
www_domain: deployer.app

www_document_root: /var/www/deployer/public
deployer_directory: /var/www/deployer
php_fcgi_port: 9000
php_display_errors: On
php_display_startup_errors: On
php_error_reporting: E_ALL & ~E_DEPRECATED & ~E_STRICT
php_request_slowlog_time: 30s
