name: Unit Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 15
      fail-fast: false
      matrix:
        php: ['7.2', '7.3']

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}
          extension-csv: mbstring, xdebug, gd, curl, pdo_mysql, pdo_pgsql, sqlite3
          coverage: none

      - name: Copy .env
        run: cp tests/env .env

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --no-suggest

      - name: Run Unit Tests
        run: composer test:unit